name: Black

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "draft/**"
      - "docs/**"
  pull_request:
    types: [ opened, reopened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: psf/black@stable